title: Code for: Barramundi Linkage Map (Hintzsche et al. 2026)
description: A Jekyll site for building the Barramundi Linkage Map
baseurl: ""       # leave blank for project sites unless using a subpath
url: ""           # leave blank for local preview
theme: minima     # or any theme you like